name : "npm publish"

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: run ci
        run: npm ci
      - name: publish
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
