name : "npm publish"

on:
  push:
    branches:
      - master
      - RED-364_init

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: publish
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
