name : "npm publish"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run ci
        run: npm ci
      - name: build
        run: npm run build

  test:
    runs-on: "ubuntu-latest"
    needs: [ build ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run ci
        run: npm ci
      - name: test:unit
        run: npm run test:unit

  publish:
    runs-on: "ubuntu-latest"
    needs: [build, test]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: run ci
        run: npm ci
      - name: publish
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
