name : "npm publish"

on:
  push:
    branches:
      - master
      - RED-364_init

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
